### ISSUE TITLE
CORS policy

### ISSUE THREAD

**Issue by cabello** [aws-samples/amazon-ivs-player-web-sample#11]
Hi,

I was using the m3u8 links in the README.md to play test feeds during development only. It was working until a few days ago. Now I get the following error in both Chrome and Firefox: 

```
Access to fetch at 'https://1b1ecb7efeb2.us-east-1.playback.live-video.net/api/video/v1/us-east-1.533826271312.channel.3NcFegvmOax6.m3u8?player_version=1.0.0' from origin 'http://localhost:3000' has been blocked by CORS policy: No 'Access-Control-Allow-Origin' header is present on the requested resource. If an opaque response serves your needs, set the request's mode to 'no-cors' to fetch the resource with CORS disabled.
```

It seems that something on the server side changed https://stackoverflow.com/questions/52412511/cors-and-request-headers-errors-on-live-streaming-using-videojs

Could CORS be allowed again please?
It's very handy to be able to connect to a always on feed, it simplifies development & testing.
Thank you.

**Comment by tonyjin** [comment]
Hey @cabello, I don't recognize that playback URL - it doesn't appear to be in our README.md based on a quick search. Is this perhaps a playback URL that you generated?

I checked our [test streams](https://github.com/aws-samples/amazon-ivs-player-web-sample#test-streams), and they all appear to be working correctly with the appropriate CORS headers.

**Comment by cabello** [comment]
Hi @tonyjin 

Thank you for the quick reply, you are correct that was a custom stream that I created, my bad. Sorry!

The videos in the README look fine 🙇
