### ISSUE TITLE
iOS Version 1.2.0: missing required architecture x86_64

### ISSUE THREAD

**Issue by esilverberg** [aws-samples/amazon-ivs-player-web-sample#17]
When attempting to upgrade AmazonIVSPlayer in my project, I see the error:

```
missing required architecture x86_64
```

It compiles just fine when I keep it at version 1.1.0.

**Comment by tonyjin** [comment]
Hello! Can you please post this issue in https://github.com/aws-samples/amazon-ivs-player-ios-sample instead?

This repo is for the web SDK.
