### ISSUE TITLE
IVSPlayer.isPlayerSupported returns true on ios safari, but timedMetadata are not handled

### ISSUE THREAD

**Issue by svenmalkus** [aws-samples/amazon-ivs-player-web-sample#18]
Hey guys,
using this [codepen example](https://codepen.io/amazon-ivs/pen/XWmjEKN) on iOS Safari the IVSPlayer.isPlayerSupported flag is true but the sdk doesn't handle timed metadata. Is there no support for this feature on iOS Safari (i did not find any information about this in the documentation)? And how can i detect support of timed-metadata if not with this flag?
Thx!

**Comment by johnBartos** [comment]
Hi @svenmalkus, timed metadata is currently unsupported in iOS Safari but we're working on it

**Comment by leidymgdev** [comment]
Hello, metadata is still currently unsupported for IOS Safari?.
