### ISSUE TITLE
Video sometimes doesn't stream when using Mac OSX Safari

### ISSUE THREAD

**Issue by DanielHudson** [aws-samples/amazon-ivs-player-web-sample#19]
I've just finished a live stream which worked well for most of our 5000 users - however we had complaints from a lot of Safari Mac OSX users stating that the stream wouldn't load.

I managed to reproduce the issue in Safari by simply refreshing any page with the IVS Player on it where it seems that the video stream will not consistently load and start playing.

When the stream does not play, there seems to be a fetch error in the console.

I'm not sure if this is Safari or IVS Player.

I notice that this can also be reproduced on the [codepen example.](https://codepen.io/amazon-ivs/pen/c3b13a2df34b60ada7756f3a2af8d2f0)

<img width="1930" alt="Screenshot 2021-01-26 at 21 31 22" src="https://user-images.githubusercontent.com/471505/105908964-d42df880-601e-11eb-91af-233f9f16cb6f.png">

**Comment by tonyjin** [comment]
Hey @DanielHudson thank you for the report. We're able to reproduce this internally and will work on a fix.

**Comment by tonyjin** [comment]
Hey @DanielHudson we've release v1.3.1, which should resolve this issue. Please let us know if you continue to see this problem.

https://docs.aws.amazon.com/ivs/latest/userguide/release-notes.html
