### ISSUE TITLE
Error handling for script tag when streaming is down

### ISSUE THREAD

**Issue by mrudangshah** [aws-samples/amazon-ivs-player-web-sample#26]
I have integrated the IVS streaming channel into React for the script tag. And now I need to handle the error of AWS channel for any errors throwing from the channel.

I have log the `player` variable and checked the properties but it does have any props related to the error.
```
script.onload = () => {
  if (IVSPlayer.isPlayerSupported) {
    const player = IVSPlayer.create();
    player.attachHTMLVideoElement(document.getElementById('video-player'));
    player.load(PLAYBACK_URL)
    player.play();
    console.log(player);
  }
}
```
As I have noticed that the wasmworker.min.js throwing the error in the console, so how to handle that error into component ?

Please review attached console.log 
![aocAa](https://user-images.githubusercontent.com/16753977/117023316-9f64c800-ad16-11eb-889d-41cc5769f023.png)

- [ ] [Mentioning](https://github.blog/2011-03-23-mention-somebody-they-re-notified/) the authors so that they can notify.
-  @johnBartos @tonyjin @hyandell @dasmalini

**Comment by tonyjin** [comment]
Hey @mrudangshah, please reach out to [AWS support](https://aws.amazon.com/premiumsupport/) for general support.

You can use the player's error handler to listen to `PlayerEventType.ERROR` events, e.g. https://github.com/aws-samples/amazon-ivs-player-web-sample/blob/master/samples/cloud-player/cloud-player.ts#L51
