### ISSUE TITLE
Repl.it fails to compile

### ISSUE THREAD

**Issue by mullicak** [aws-samples/amazon-ivs-player-web-sample#27]
**Describe the bug**
Repl.it gives the following error in the Console after clicking "Run", per the instructions in the README.md:
ERROR in ./node_modules/amazon-ivs-player/dist/index.js
Module not found: Error: Can't resolve 'bowser' in '/home/runner/amazon-ivs-player-web-sample/node_modules/amazon-ivs-player/dist'
 @ ./node_modules/amazon-ivs-player/dist/index.js 6:92432-92449
 @ ./samples/npm-sdk/npm-sdk.ts

**To Reproduce**
Follow the steps in the "Live Demo" section of the README.me:
1. Visit https://repl.it/github/aws-samples/amazon-ivs-player-web-sample and sign up for an account
2. Leave the default repl.it configuration (select language: Node.js, configure the run button: npm start) and click "Done"
3. Click the "Run" button
4. Wait for npm install and npm start to complete. 

**Expected behavior**
In Repl.it, you should see Compiled successfully in the console when done

**Screenshots**
If applicable, add screenshots to help explain your problem, e.g. of the player behavior you're seeing or of the console output.

**Desktop (please complete the following information):**
 - OS: Mac OS Big Sure
 - Browser: Chrome (91.0.4472.77 (Official Build) (x86_64)) 
<img width="571" alt="Screen Shot 2021-05-29 at 1 33 59 PM" src="https://user-images.githubusercontent.com/69986091/120081715-96041c80-c084-11eb-893b-31b48f7d697f.png">
and Firefox (78.10.1esr (64-bit))

**Additional context**

**Comment by tonyjin** [comment]
Thanks for the report, this should be resolved now by https://github.com/aws-samples/amazon-ivs-player-web-sample/pull/28. I noticed that installing npm packages via the repl.it demo is pretty slow - I generally get a better experience when pulling the repo down and installing locally.
