### ISSUE TITLE
AWS IVS Player freezes IE11 (event without initializing it)

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [aws-samples/amazon-ivs-player-web-sample#5]
We have implemented the AWS IVS player in our react app (with this approach: https://github.com/cm-wada-yusuke/amazon-ivs-react-js-sample/blob/master/src/AmazonIVSWorkaround.js)

But: even if we don't show the player (the video player react component is not rendered), IE freezes completely - we can't even open the developer tools in IE11.

Also there is no clear error message (only SYNTAX ERROR, but no further details or error messages), but it appears to happen here: 

![WhatsApp Image 2020-09-03 at 10 14 09](https://user-images.githubusercontent.com/10075/92093865-1c305280-edd4-11ea-8afd-9f941cd0814b.jpeg)

I couldn't find any compability list, so I expect that IE 11 should still work, since it's still supported from Microsoft?

We have many business customers which still (unfortunately) rely on IE 11, so this is a big thing for us, if IVS doesn't support IE11?

**Comment by tonyjin** [comment]
Hello, our browser & platform requirements list is here: https://docs.aws.amazon.com/ivs/latest/userguide/ISP.html. We unfortunately don't support IE11 at the moment. Do you mind opening a ticket with AWS support with your issue and use case?
