### ISSUE TITLE
Uncaught Error: Module "events" has been externalized for browser compatibility. Cannot access "events.EventEmitter" in client code

### ISSUE THREAD

**Issue by dtgbao** [aws-samples/amazon-ivs-player-web-sample#56]
**Describe the bug**
Error appear in console and cannot play video when running [npm-sdk sample code](https://github.com/aws-samples/amazon-ivs-player-web-sample/blob/master/samples/npm-sdk/npm-sdk.ts) on [Vitejs](https://vitejs.dev/)

**Package info**
"amazon-ivs-player": "^1.12.0"

**Sample Code:**
https://stackblitz.com/edit/vitejs-aws-ivs?file=src%2Fplayer.ts&terminal=dev

**Screenshots**
<img width="530" alt="image" src="https://user-images.githubusercontent.com/42051607/187055384-ca9d4326-8402-4e11-9425-8341216c3343.png">

**Comment by johnBartos** [comment]
I'm not familiar with Vite, is this an issue with that library? I see something similar in their issue tracker https://github.com/vitejs/vite/discussions/4479

If there's an improvement we can make to support Vite, let me know.

**Comment by francis-robert** [comment]
Webpack defaults to using [node-libs-browser](https://github.com/webpack/node-libs-browser) when specifying the web platform. This means that any time it would encounter any of the known compatible node libs it'll be replaced with an equivalent web implementation. In our case, that happens with the `events` module.

`Vite`, on the other hand is built on top of [rollup](https://rollupjs.org/guide/en/) which doesn't include this behavior by default but gives you the ability to add it in with its flexible configuration.

There's an [open issue](https://github.com/vitejs/vite/issues/7821) in the Vite repo actively discussing this.

Closing as this is a bundler issue and not a player nor sample bug
