### ISSUE TITLE
Chrome doesn't play on Windows

### ISSUE THREAD

**Issue by h0jeZvgoxFepBQ2C** [aws-samples/amazon-ivs-player-web-sample#7]
I dunno why, but following (slightly adapted) code, doesn't work on windows with chrome..
Player just stays black, loads, sometimes shows a still picture after long time, RAM consumption goes up drastically.. But no errors.

wasm files are delivered correctly, are not transpiled and have a correct mime encoding delivered by nginx.

```jsx
import React, { useEffect, useRef, useState } from 'react';
import videojs from 'video.js';
import {
   registerIVSTech,
} from 'amazon-ivs-player';

import wasmWorkerPath from 'amazon-ivs-player/dist/assets/amazon-ivs-wasmworker.min.js'
import wasmBinaryPath from 'amazon-ivs-player/dist/assets/amazon-ivs-wasmworker.min.wasm'

const createAbsolutePath = (assetPath) => new URL(assetPath, document.URL).toString();

export default function AmazonIvsPlayer({ props }) {

  const streamSource = "https://d6hwdeiig07o4.cloudfront.net/ivs/956482054022/cTo5UpKS07do/2020-07-13T22-54-42.188Z/OgRXMLtq8M11/media/hls/master.m3u8"
  
  let player = null;

   useEffect(() => {
     console.log("absolute path", createAbsolutePath(wasmWorkerPath))

     registerIVSTech(videojs, {
         wasmWorker: createAbsolutePath(wasmWorkerPath),
         wasmBinary: createAbsolutePath(wasmBinaryPath),
     });
     // registerIVSQualityPlugin(videojs)

     player = videojs('amazon-ivs-videojs', {
         techOrder: ["AmazonIVS"], 
         controlBar: {
           fullscreenToggle: false,
           pictureInPictureToggle: false
         },
         autoplay: false,
         logLevel: "debug",
         src: streamSource
     }, () => {
        console.log('Player is ready to use!', player);
         player.src(streamSource)
     })

     console.log('Player is ready to use!', player);
     // player.enableIVSQualityPlugin(); 
   }, [streamSource])


  return (
     <div className="amazon-container text-center">
      <video id="amazon-ivs-videojs" className="video-js vjs-theme-city" controls/>
    </div>
  )
}
```

All other browsers work completely fine, Safari, FF,... Also chrome on OSX works fine.. Just windows :(

**Comment by tonyjin** [comment]
Thanks for the report. Few questions:
- What version of Windows & what version of Chrome?
- Does this CodePen work for you on Windows Chrome?
  - https://codepen.io/amazon-ivs/pen/bdc01e977102051eae5fb85482f88276
- Do you have any extensions installed or browser flags enabled that could be affecting playback?

**Comment by h0jeZvgoxFepBQ2C** [comment]
Omfg... We found out why there was this strange behaviour.. 

We were using sentry-react... After removing it, the player works flawelessly... omg, I spent so many hours...
Maybe you should add this to your readme or know issues page.. May help to save someones work time...

**Comment by johnBartos** [comment]
@h0jeZvgoxFepBQ2C Glad that you managed to resolve your issue, and thanks for reporting it. People searching for similar issues should see this, so I don't believe we need to further document it.
