### ISSUE TITLE
"Method called on deleted player instance" warning when using IVSQualityPlugin

### ISSUE THREAD

**Issue by nightpool** [aws-samples/amazon-ivs-player-web-sample#9]
### [Minimal Reproduction](https://codesandbox.io/s/adoring-dawn-edecv)

-----

### Description

When using the IVSQualityPlugin, any attempt to `.dispose()` of the videojs instance (for example, in the cleanup function of a React component) will trigger a console warning "Method called on deleted player instance". This is because the IVS Quality Plugin is attempting to unregister its event handlers after the IVS `core` is already disposed:

<img width="570" alt="image" src="https://user-images.githubusercontent.com/233815/93514739-92b17200-f8f5-11ea-90e7-736943d3b47e.png">

<img width="592" alt="image" src="https://user-images.githubusercontent.com/233815/93514914-c4c2d400-f8f5-11ea-889e-0fa345409449.png">

This is confusing for implementors, because they may think mistakenly that they've made an implementation error and somehow kept around an old instance of the player, which might lead to a memory leak. In fact, there is no error and the disposal completed successfully.

**Comment by johnBartos** [comment]
@nightpool Thanks for the detailed report and repro example. I've confirmed the issue and we'll work on a fix.

**Comment by nightpool** [comment]
Thanks John! I know it's really a pretty trivial issue, but it did give me a small stumble when working on my integration :)

**Comment by tonyjin** [comment]
@nightpool this should be resolved with v1.3.0, please let us know if you still see this.

https://docs.aws.amazon.com/ivs/latest/userguide/release-notes.html
